# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Build LibreSSL
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=install_dir -DBUILD_SHARED_LIBS=1
        cmake --build . --config RelWithDebInfo
        cmake --install . --config RelWithDebInfo
        New-Item -ItemType directory -Force .\deploy\LibreSSL\bin\desktop\x64
        Copy-Item .\install_dir\include -Recurse -Destination .\deploy\LibreSSL\sdk\include
        Copy-Item .\crypto\RelWithDebInfo\libcrypto.dll -Destination .\deploy\LibreSSL\bin\desktop\x64\libcrypto.dll
        Copy-Item .\crypto\RelWithDebInfo\libcrypto.exp -Destination .\deploy\LibreSSL\bin\desktop\x64\libcrypto.exp
        Copy-Item .\crypto\RelWithDebInfo\libcrypto.lib -Destination .\deploy\LibreSSL\bin\desktop\x64\libcrypto.lib
        Copy-Item .\crypto\RelWithDebInfo\libcrypto.pdb -Destination .\deploy\LibreSSL\bin\desktop\x64\libcrypto.pdb
        Compress-Archive -Path .\deploy\*  -DestinationPath LibreSSL.zip
